###############################################################################
# INPUT DATA PATHS
###############################################################################
input_data:
  # Path to cisTopic object
  cisTopic_obj_fname: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/cistopic_obj.pkl"

  # Path to gene expression AnnData file
  GEX_anndata_fname: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/adata_final.h5ad"

  # Folder containing region set files
  region_set_folder: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/region_sets"

  # Paths to motif ranking/score databases
  ctx_db_fname: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/input/mESC.regions_vs_motifs.rankings.feather"
  dem_db_fname: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/input/mESC.regions_vs_motifs.scores.feather"

  # Path to motif annotations
  path_to_motif_annotations: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/input/motifs-v10-nr.mgi-m0.00001-o0.0.tbl"

###############################################################################
# OUTPUT DATA PATHS
###############################################################################
output_data:
  # Combined GEX-ACC Mudata
  combined_GEX_ACC_mudata: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/ACC_GEX.h5mu"

  # Motif enrichment results (DEM, CisTarget) in HDF5 + HTML
  dem_result_fname: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/dem_results.hdf5"
  ctx_result_fname: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/ctx_results.hdf5"
  output_fname_dem_html: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/dem_results.html"
  output_fname_ctx_html: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/ctx_results.html"

  # Cistromes in H5AD format
  cistromes_direct: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/cistromes_direct.h5ad"
  cistromes_extended: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/cistromes_extended.h5ad"

  # TF names list
  tf_names: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/tf_names.txt"

  # Genome annotations
  genome_annotation: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/genome_annotation.tsv"
  chromsizes: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/chromsizes.tsv"

  # Search space (region-based)
  search_space: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/search_space.tsv"

  # Adjacency outputs: TF-to-gene and region-to-gene
  tf_to_gene_adjacencies: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/tf_to_gene_adj.tsv"
  region_to_gene_adjacencies: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/region_to_gene_adj.tsv"

  # eGRN outputs
  eRegulons_direct: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/eRegulon_direct.tsv"
  eRegulons_extended: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/eRegulons_extended.tsv"

  # AUCell outputs
  AUCell_direct: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/AUCell_direct.h5mu"
  AUCell_extended: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/AUCell_extended.h5mu"

  # Final scenicplus mudata object
  scplus_mdata: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/outs/scplusmdata.h5mu"

###############################################################################
# GENERAL PARAMETERS
###############################################################################
params_general:
  temp_dir: "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.GRN_BENCHMARKING.MOELLER/SCENIC_PLUS/tmp"
  n_cpu: 1
  seed: 666

###############################################################################
# DATA PREPARATION PARAMETERS
###############################################################################
params_data_preparation:
  # Prepare_GEX_ACC
  bc_transform_func: "\"lambda x: f'{x}'\""
  is_multiome: True
  key_to_group_by: ""
  nr_cells_per_metacells: 10

  # Prepare_menr
  direct_annotation: "Direct_annot"
  extended_annotation: "Orthology_annot"

  # Download_genome_annotations
  species: "mmusculus"
  biomart_host: "http://www.ensembl.org"

  # Search_space
  search_space_upstream: "1000 5000"
  search_space_downstream: "1000 5000"
  search_space_extend_tss: "10 10"

###############################################################################
# MOTIF ENRICHMENT PARAMETERS
###############################################################################
params_motif_enrichment:
  species: "mus_musculus"
  annotation_version: "v9-nr"
  motif_similarity_fdr: 0.001
  orthologous_identity_threshold: 0.0
  annotations_to_use: "Direct_annot Orthology_annot"

  # DEM parameters
  fraction_overlap_w_dem_database: 0.2
  dem_max_bg_regions: 1000
  dem_balance_number_of_promoters: True
  dem_promoter_space: 500
  dem_adj_pval_thr: 1
  dem_log2fc_thr: 0.1
  dem_mean_fg_thr: 0.005
  dem_motif_hit_thr: 0.5

  # CisTarget parameters
  fraction_overlap_w_ctx_database: 0.1
  ctx_auc_threshold: 0.005
  ctx_nes_threshold: 2.0
  ctx_rank_threshold: 0.1

###############################################################################
# INFERENCE PARAMETERS
###############################################################################
params_inference:
  # TF-to-gene
  tf_to_gene_importance_method: "GBM"

  # Region-to-gene
  region_to_gene_importance_method: "GBM"
  region_to_gene_correlation_method: "SR"

  # eGRN inference
  order_regions_to_genes_by: "importance"
  order_TFs_to_genes_by: "importance"
  gsea_n_perm: 1000
  quantile_thresholds_region_to_gene: "0.85 0.90 0.95"
  top_n_regionTogenes_per_gene: "5 10 15"
  top_n_regionTogenes_per_region: ""
  min_regions_per_gene: 0
  rho_threshold: 0.05
  min_target_genes: 10
